DROP DATABASE IF EXISTS restaurante_canasto;
CREATE DATABASE restaurante_canasto;
USE restaurante_canasto;

-- =========================
-- ESTADOS
-- =========================
CREATE TABLE CANASTO_ESTADOS_TB(
    ID_ESTADO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

-- =========================
-- ROLES
-- =========================
CREATE TABLE CANASTO_ROLES_TB(
    ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- USUARIOS
-- =========================
CREATE TABLE CANASTO_USUARIOS_TB(
    IDENTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100),
    APELLIDO_MATERNO VARCHAR(100),
    CORREO VARCHAR(150) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHA_INGRESO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    ID_ROL INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO),
    FOREIGN KEY (ID_ROL) REFERENCES CANASTO_ROLES_TB(ID_ROL)
);

-- =========================
-- CATEGORÍAS
-- =========================
CREATE TABLE CANASTO_CATEGORIAS_MENU_TB(
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(100),
    DESCRIPCION VARCHAR(1000),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- PRODUCTOS
-- =========================
CREATE TABLE CANASTO_PRODUCTOS_TB(
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(1000),
    PRECIO DECIMAL(10,2),
    ID_CATEGORIA INT,
    IMAGEN_RUTA VARCHAR(1000),
    ID_ESTADO INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CANASTO_CATEGORIAS_MENU_TB(ID_CATEGORIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- PEDIDOS
-- =========================
CREATE TABLE CANASTO_PEDIDOS_TB(
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICACION INT,
    NUMERO_MESA INT NOT NULL,
    OBSERVACIONES VARCHAR(1000),
    FECHA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (IDENTIFICACION) REFERENCES CANASTO_USUARIOS_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- DETALLE PEDIDO
-- =========================
CREATE TABLE CANASTO_DETALLE_PEDIDO_TB(
    ID_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    ID_ESTADO INT,
    FOREIGN KEY (ID_PEDIDO) REFERENCES CANASTO_PEDIDOS_TB(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES CANASTO_PRODUCTOS_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- MODIFICADORES
-- =========================
CREATE TABLE CANASTO_MODIFICADORES_TB(
    ID_MODIFICADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    MIN_SELECCION INT DEFAULT 0,
    MAX_SELECCION INT DEFAULT 1,
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- OPCIONES MODIFICADOR
-- =========================
CREATE TABLE CANASTO_MODIFICADOR_OPCIONES_TB(
    ID_OPCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_MODIFICADOR INT,
    NOMBRE VARCHAR(100),
    PRECIO_EXTRA DECIMAL(10,2) DEFAULT 0,
    ID_ESTADO INT,
    FOREIGN KEY (ID_MODIFICADOR) REFERENCES CANASTO_MODIFICADORES_TB(ID_MODIFICADOR),
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- RELACIÓN PRODUCTO - MODIFICADOR
-- =========================
CREATE TABLE CANASTO_PRODUCTO_MODIFICADOR_TB(
    ID_PRODUCTO INT,
    ID_MODIFICADOR INT,
    PRIMARY KEY (ID_PRODUCTO, ID_MODIFICADOR),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES CANASTO_PRODUCTOS_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_MODIFICADOR) REFERENCES CANASTO_MODIFICADORES_TB(ID_MODIFICADOR)
);

-- =========================
-- IMPUESTOS
-- =========================
CREATE TABLE CANASTO_IMPUESTOS_TB(
    ID_IMPUESTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    PORCENTAJE DECIMAL(5,2),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- MÉTODOS DE PAGO
-- =========================
CREATE TABLE CANASTO_METODOS_PAGO_TB(
    ID_METODO_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- FACTURAS
-- =========================
CREATE TABLE CANASTO_FACTURAS_TB(
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT,
    FECHA_FACTURA DATETIME DEFAULT CURRENT_TIMESTAMP,
    SUBTOTAL DECIMAL(10,2),
    ID_IMPUESTO INT,
    TOTAL DECIMAL(10,2),
    ID_METODO_PAGO INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PEDIDO) REFERENCES CANASTO_PEDIDOS_TB(ID_PEDIDO),
    FOREIGN KEY (ID_IMPUESTO) REFERENCES CANASTO_IMPUESTOS_TB(ID_IMPUESTO),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES CANASTO_METODOS_PAGO_TB(ID_METODO_PAGO),
    FOREIGN KEY (ID_ESTADO) REFERENCES CANASTO_ESTADOS_TB(ID_ESTADO)
);

-- =========================
-- INSERTS BASE
-- =========================

INSERT INTO CANASTO_ESTADOS_TB VALUES
(1,'ACTIVO'),
(2,'INACTIVO'),
(3,'PENDIENTE'),
(4,'EN_PROCESO'),
(5,'COMPLETADO');

-- ROLES (LOS 4 QUE QUERÍAS)
INSERT INTO CANASTO_ROLES_TB (NOMBRE,DESCRIPCION,ID_ESTADO) VALUES
('ADMIN','Administrador del sistema',1),
('COCINERO','Cocina / preparación',1),
('MESERO','Atiende pedidos',1);

INSERT INTO CANASTO_USUARIOS_TB
(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, CONTRASENA, ID_ESTADO, ID_ROL)
VALUES
('Admin', 'Admin', 'Sistema', 'admin@gmail.com', 'admin123', 1, 1),
('Melissa', 'Perez', 'Lopez', 'melissa@gmail.com', '1234', 1, 1),
('Gustavo', 'Ortiz', 'Ramirez', 'gustavo@gmail.com', '1234', 1, 1),
('Kendall', 'Leibre', 'Mora', 'kendall@gmail.com', '1234', 1, 3),
('Ari', 'Soto', 'Vargas', 'ari@gmail.com', '1234', 1, 3),
('Santiago', 'Azofeifa', 'Porras', 'santi@gmail.com', '1234', 1, 2),
('Miguel', 'Rojas', 'Elizondo', 'miguel@gmail.com', '1234', 1, 2);

-- CATEGORÍAS
INSERT INTO CANASTO_CATEGORIAS_MENU_TB (NOMBRE_CATEGORIA,DESCRIPCION,ID_ESTADO) VALUES
('Desayunos','Platos tradicionales',1),
('Bebidas','Bebidas varias',1),
('Almuerzos','Platos fuertes',1),
('Pizzas','Variedad pizzas',1);


-- RELACIÓN PRODUCTO - MODIFICADOR 


-- IMPUESTO
INSERT INTO CANASTO_IMPUESTOS_TB (NOMBRE,PORCENTAJE,ID_ESTADO)
VALUES ('IVA',13,1);

-- MÉTODOS DE PAGO
INSERT INTO CANASTO_METODOS_PAGO_TB (NOMBRE,ID_ESTADO)
VALUES ('Efectivo',1),('Tarjeta',1);

/* =========================
iNSERTS DE PRUEBA
========================= */
/* =========================
   PIZZA S
========================= */

INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Pizza S','Pizza de 4 slices a la leña',5000,4,1);

SET @PIZZA_S = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES 
('Elige el sabor','Sabores disponibles',1,1,1);

SET @MOD_S = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PIZZA_S,@MOD_S);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
(ID_MODIFICADOR,NOMBRE,PRECIO_EXTRA,ID_ESTADO)
VALUES
(@MOD_S,'Canasto',3000,1),
(@MOD_S,'Jamon',0,1),
(@MOD_S,'Jamon y hongos',2000,1),
(@MOD_S,'Peperonni',2000,1),
(@MOD_S,'Margarita',2000,1),
(@MOD_S,'Napolitana',2000,1),
(@MOD_S,'Suprema',2000,1),
(@MOD_S,'Hawainna',2000,1),
(@MOD_S,'Brasileña',2000,1),
(@MOD_S,'Mexicana',2000,1),
(@MOD_S,'Argentina',2000,1),
(@MOD_S,'Salame',2000,1),
(@MOD_S,'Vegetariana',2000,1),
(@MOD_S,'Cuatro Estaciones',2000,1),
(@MOD_S,'Pollo',2000,1),
(@MOD_S,'Carnes y Vegetales',2000,1),
(@MOD_S,'Especial de Carne',2000,1);


/* =========================
   PIZZA M
========================= */

INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Pizza M','Pizza de 8 slices a la leña',9000,4,1);

SET @PIZZA_M = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES 
('Elige el sabor','Sabores disponibles',1,1,1);

SET @MOD_M = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PIZZA_M,@MOD_M);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
(ID_MODIFICADOR,NOMBRE,PRECIO_EXTRA,ID_ESTADO)
VALUES
(@MOD_M,'Canasto',3000,1),
(@MOD_M,'Jamon',0,1),
(@MOD_M,'Jamon y hongos',1000,1),
(@MOD_M,'Peperonni',1000,1),
(@MOD_M,'Margarita',1000,1),
(@MOD_M,'Napolitana',1000,1),
(@MOD_M,'Suprema',1000,1),
(@MOD_M,'Hawainna',1000,1),
(@MOD_M,'Brasileña',1000,1),
(@MOD_M,'Mexicana',1000,1),
(@MOD_M,'Argentina',1000,1),
(@MOD_M,'Salame',1000,1),
(@MOD_M,'Vegetariana',1000,1),
(@MOD_M,'Cuatro Estaciones',1000,1),
(@MOD_M,'Pollo',1000,1),
(@MOD_M,'Carnes y Vegetales',1000,1),
(@MOD_M,'Especial de Carne',1000,1);


/* =========================
   PIZZA L
========================= */

INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Pizza L','Pizza de 12 slices a la leña',12000,4,1);

SET @PIZZA_L = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES 
('Elige el sabor','Sabores disponibles',1,1,1);

SET @MOD_L = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PIZZA_L,@MOD_L);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
(ID_MODIFICADOR,NOMBRE,PRECIO_EXTRA,ID_ESTADO)
VALUES
(@MOD_L,'Canasto',2000,1),
(@MOD_L,'Jamon',0,1),
(@MOD_L,'Jamon y hongos',1000,1),
(@MOD_L,'Peperonni',1000,1),
(@MOD_L,'Margarita',1000,1),
(@MOD_L,'Napolitana',1000,1),
(@MOD_L,'Suprema',1000,1),
(@MOD_L,'Hawainna',1000,1),
(@MOD_L,'Brasileña',1000,1),
(@MOD_L,'Mexicana',1000,1),
(@MOD_L,'Argentina',1000,1),
(@MOD_L,'Salame',1000,1),
(@MOD_L,'Vegetariana',1000,1),
(@MOD_L,'Cuatro Estaciones',1000,1),
(@MOD_L,'Pollo',1000,1),
(@MOD_L,'Carnes y Vegetales',1000,1),
(@MOD_L,'Especial de Carne',1000,1);


/* =========================
   PIZZA XL
========================= */

INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Pizza XL','Pizza de 16 slices a la leña',14000,4,1);

SET @PIZZA_XL = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES 
('Elige el sabor','Sabores disponibles',1,1,1);

SET @MOD_XL = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PIZZA_XL,@MOD_XL);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
(ID_MODIFICADOR,NOMBRE,PRECIO_EXTRA,ID_ESTADO)
VALUES
(@MOD_XL,'Canasto',2000,1),
(@MOD_XL,'Jamon',0,1),
(@MOD_XL,'Jamon y hongos',1000,1),
(@MOD_XL,'Peperonni',1000,1),
(@MOD_XL,'Margarita',1000,1),
(@MOD_XL,'Napolitana',1000,1),
(@MOD_XL,'Suprema',1000,1),
(@MOD_XL,'Hawainna',1000,1),
(@MOD_XL,'Brasileña',1000,1),
(@MOD_XL,'Mexicana',1000,1),
(@MOD_XL,'Argentina',1000,1),
(@MOD_XL,'Salame',1000,1),
(@MOD_XL,'Vegetariana',1000,1),
(@MOD_XL,'Cuatro Estaciones',1000,1),
(@MOD_XL,'Pollo',1000,1),
(@MOD_XL,'Carnes y Vegetales',1000,1),
(@MOD_XL,'Especial de Carne',1000,1);

/* =========================
CASADOS
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Casado','Plato completo con arroz, frijoles, ensalada y fresco natural',5800,3,1);

SET @CASADO = LAST_INSERT_ID();

-- MOD 1 PROTEINA
INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES ('Elige tu casado favorito','Proteina',1,1,1);

SET @M1 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@CASADO,@M1);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M1,'Chuleta Ahumada',0,1),
(NULL,@M1,'Filet de Tilapia',0,1),
(NULL,@M1,'Chuleta Corriente',0,1),
(NULL,@M1,'Carne en Salsa',0,1),
(NULL,@M1,'Pollo en Salsa',0,1),
(NULL,@M1,'Bistec de Res',0,1),
(NULL,@M1,'Bistec de Cerdo',0,1),
(NULL,@M1,'Carne Desmechada',0,1),
(NULL,@M1,'Pollo a la Plancha',0,1),
(NULL,@M1,'Higado',0,1),
(NULL,@M1,'Pollo Asado',700,1),
(NULL,@M1,'Pollo Frito',700,1);

-- MOD 2 ENSALADA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Ensalada','Tipo de ensalada',1,1,1);

SET @M2 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@CASADO,@M2);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M2,'Ensalada de Caracolitos',0,1),
(NULL,@M2,'Ensalada Rusa',0,1),
(NULL,@M2,'Ensalada Verde',0,1);

-- MOD 3 BEBIDA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Bebida','Bebida del casado',1,1,1);

SET @M3 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@CASADO,@M3);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M3,'Cas',0,1),
(NULL,@M3,'Arroz con Piña',0,1),
(NULL,@M3,'Chia con Tamarindo',0,1),
(NULL,@M3,'Coca Cola 500ml',2000,1),
(NULL,@M3,'Fanta Kolita 500ml',2000,1),
(NULL,@M3,'Fuze Tea Melocoton',2000,1),
(NULL,@M3,'Coca Cola Zero',2000,1);

-- MOD 4 ELIMINAR
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Eliminar ingredientes','Quitar ingredientes',0,4,1);

SET @M4 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@CASADO,@M4);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M4,'Sin arroz',0,1),
(NULL,@M4,'Sin frijoles',0,1),
(NULL,@M4,'Sin picadillo',0,1),
(NULL,@M4,'Sin ensalada',0,1);

-- MOD 5 EXTRA PROTEINA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Agregar proteina','Extras',0,10,1);

SET @M5 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@CASADO,@M5);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M5,'Chuleta Ahumada',2000,1),
(NULL,@M5,'Filet de Tilapia',2000,1),
(NULL,@M5,'Carne en Salsa',2000,1),
(NULL,@M5,'Pollo en Salsa',2000,1),
(NULL,@M5,'Bistec de Res',2000,1);
/* =========================
PASTAS
========================= */

/* =========================
OLLA DE CARNE
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
VALUES (NULL,'Olla de Carne','Olla tradicional completa',7900,3,NULL,1);

SET @OLLA = LAST_INSERT_ID();

-- EXTRA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Extras','Agregar ingredientes',0,2,1);

SET @M1 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@OLLA,@M1);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M1,'Extra Arroz',2000,1),
(NULL,@M1,'Extra Tortilla',1000,1);

-- ELIMINAR
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Eliminar ingredientes','Quitar ingredientes',0,10,1);

SET @M2 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@OLLA,@M2);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M2,'Yuca',0,1),
(NULL,@M2,'Elote',0,1),
(NULL,@M2,'Chayote',0,1),
(NULL,@M2,'Papa',0,1);
/* =========================
PINTO
========================= */

INSERT INTO CANASTO_PRODUCTOS_TB 
VALUES (NULL,'Pinto','Desayuno tradicional',4800,1,NULL,1);

SET @PINTO = LAST_INSERT_ID();

-- MOD 1
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Primera eleccion','',1,1,1);

SET @M1 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PINTO,@M1);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M1,'Huevo',0,1),
(NULL,@M1,'Salchichon',0,1),
(NULL,@M1,'Natilla',0,1),
(NULL,@M1,'Queso',0,1),
(NULL,@M1,'Maduro',0,1);

-- MOD 2
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Segunda eleccion','',1,1,1);

SET @M2 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PINTO,@M2);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M2,'Pollo Asado',200,1),
(NULL,@M2,'Costilla Asada',200,1);

-- MOD 3
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Tercera eleccion','',1,1,1);

SET @M3 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PINTO,@M3);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M3,'Pan',0,1),
(NULL,@M3,'Tortilla Palmeada',0,1);

-- MOD 4 BEBIDA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Bebida','',1,1,1);

SET @M4 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PINTO,@M4);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M4,'Cafe Negro',0,1),
(NULL,@M4,'Cafe con Leche',0,1),
(NULL,@M4,'Coca Cola',2000,1);
/* =========================
PUPUSAS
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
VALUES (NULL,'Pupusa','Pupusas salvadoreñas',3200,3,NULL,1);

SET @PUPUSA = LAST_INSERT_ID();

-- SABOR
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Tipo de pupusa','',1,1,1);

SET @M1 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PUPUSA,@M1);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M1,'Mixta Extra Queso',500,1),
(NULL,@M1,'Mixta Sencilla',0,1),
(NULL,@M1,'Chicharron',0,1),
(NULL,@M1,'Frijol',0,1),
(NULL,@M1,'Queso',0,1),
(NULL,@M1,'Carne Mechada',0,1),
(NULL,@M1,'Pollo',0,1);

-- ENSALADA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Ensalada','',1,1,1);

SET @M2 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PUPUSA,@M2);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M2,'Sin Chile',0,1),
(NULL,@M2,'Con Chile',0,1);

-- EXTRAS
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Extras','',0,3,1);

SET @M3 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PUPUSA,@M3);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M3,'Queso',1500,1),
(NULL,@M3,'Pollo',1500,1),
(NULL,@M3,'Carne Mechada',1500,1);

-- BEBIDA
INSERT INTO CANASTO_MODIFICADORES_TB VALUES
(NULL,'Bebida','',0,1,1);

SET @M4 = LAST_INSERT_ID();
INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB VALUES (@PUPUSA,@M4);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB VALUES
(NULL,@M4,'Coca Cola',2000,1),
(NULL,@M4,'Fuze Tea',2000,1),
(NULL,@M4,'Cas',1500,1);

/* =========================
GASEOSA 500 ML
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Gaseosa 500 ml','Bebida gaseosa personal',2000,2,1);

SET @G500 = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
(NOMBRE,DESCRIPCION,MIN_SELECCION,MAX_SELECCION,ID_ESTADO)
VALUES 
('Elige tu gaseosa favorita','',1,1,1);

SET @M1 = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB 
VALUES (@G500,@M1);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
(ID_MODIFICADOR,NOMBRE,PRECIO_EXTRA,ID_ESTADO)
VALUES
(@M1,'Coca Cola 500ml',0,1),
(@M1,'Coca Cola Zero 500ml',0,1),
(@M1,'Fanta Kolita 500ml',0,1),
(@M1,'Fanta Naranja 500ml',0,1),
(@M1,'Fanta Uva 500ml',0,1),
(@M1,'Canada Dry 500ml',0,1),
(@M1,'Fresca 500ml',0,1),
(@M1,'Fuze Tea Melocoton 500ml',0,1),
(@M1,'Fuze Tea Limon 500ml',0,1);
/* =========================
GASEOSA 2L
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Gaseosa 2L','Bebida gaseosa familiar',3500,2,1);

SET @G2L = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
VALUES (NULL,'Elige tu gaseosa favorita','',1,1,1);

SET @M2 = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB 
VALUES (@G2L,@M2);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
VALUES
(NULL,@M2,'Coca Cola 2L',0,1),
(NULL,@M2,'Coca Cola Zero 2L',0,1),
(NULL,@M2,'Fanta Kolita 2L',0,1),
(NULL,@M2,'Fanta Naranja 2L',0,1),
(NULL,@M2,'Fanta Uva 2L',0,1),
(NULL,@M2,'Canada Dry 2L',0,1),
(NULL,@M2,'Fresca 2L',0,1),
(NULL,@M2,'Fuze Tea Melocoton 2L',0,1),
(NULL,@M2,'Fuze Tea Limon 2L',0,1);
/* =========================
BEBIDAS CALIENTES
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Bebidas calientes','Bebidas calientes tradicionales',1500,2,1);

SET @CAL = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
VALUES (NULL,'Elige tu bebida caliente','',1,1,1);

SET @M4 = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB 
VALUES (@CAL,@M4);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
VALUES
(NULL,@M4,'Cafe Negro',0,1),
(NULL,@M4,'Cafe con Leche',0,1),
(NULL,@M4,'Chocolate',300,1),
(NULL,@M4,'Agua Dulce en Agua',300,1),
(NULL,@M4,'Agua Dulce en Leche',300,1);
/* =========================
NATURAL
========================= */
INSERT INTO CANASTO_PRODUCTOS_TB 
(NOMBRE,DESCRIPCION,PRECIO,ID_CATEGORIA,ID_ESTADO)
VALUES 
('Natural','Bebida natural fresca',1500,2,1);

SET @NAT = LAST_INSERT_ID();

INSERT INTO CANASTO_MODIFICADORES_TB 
VALUES (NULL,'Elige tu natural favorito','',1,1,1);

SET @M3 = LAST_INSERT_ID();

INSERT INTO CANASTO_PRODUCTO_MODIFICADOR_TB 
VALUES (@NAT,@M3);

INSERT INTO CANASTO_MODIFICADOR_OPCIONES_TB 
VALUES
(NULL,@M3,'Cas',0,1),
(NULL,@M3,'Arroz con Piña',0,1);

SET SQL_SAFE_UPDATES = 0;
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pizza_s.jpg' WHERE NOMBRE = 'Pizza S';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pizza_m.jpg' WHERE NOMBRE = 'Pizza M';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pizza_l.jpg' WHERE NOMBRE = 'Pizza L';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pizza_xl.jpg' WHERE NOMBRE = 'Pizza XL';

-- 3. Le asignamos el nombre de la foto a todos los platillos fuertes
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'casado.jpg' WHERE NOMBRE = 'Casado';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'olla_carne.jpg' WHERE NOMBRE = 'Olla de Carne';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pinto.jpg' WHERE NOMBRE = 'Pinto';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'pupusa.jpg' WHERE NOMBRE = 'Pupusa';

-- 4. Le asignamos el nombre de la foto a todas las bebidas
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'gaseosa_500.jpg' WHERE NOMBRE = 'Gaseosa 500 ml';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'gaseosa_2l.jpg' WHERE NOMBRE = 'Gaseosa 2L';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'bebida_caliente.jpg' WHERE NOMBRE = 'Bebidas calientes';
UPDATE CANASTO_PRODUCTOS_TB SET IMAGEN_RUTA = 'natural.jpg' WHERE NOMBRE = 'Natural';

